### ISSUE TITLE
"Packages installation failed" Error on Windows Server 2019 and Windows 11

### ISSUE THREAD

**Issue by RicardoAALL** [japa/core#69] opened 2023-05-02 20:45 UTC
### Package version

4.0.0

### Describe the bug

Unable to install japa on Windows Server 2019 and Windows 11 following the [Installation and Usage](https://japa.dev/docs/usage) guide in the documentation.

Executing `npm init japa@latest` in the project root and following the prompts results in the following error after the bin folder is created.

```
> Select the tests reporter · @japa/spec-reporter
> Select the assertion library · @japa/expect
> Select additional plugins · No items were selected
> Select the project type · TypeScript ESM
> Want us to create a sample test? (y/N) · false

CREATE: bin/test.ts
CREATE: bin/japa_types.ts


× Packages installation failed
```

The above error happens regardless of what options are chosen during the installation prompt.

**Comment by Julien-R44** [comment] 2023-05-03 18:04
No idea for Windows Server. However I am on Windows 11 and it works perfectly

The problem may comes from here: https://github.com/japa/create-japa/blob/develop/index.ts#L352

The install function comes from the `mrm-core` library and its definitions is here : https://github.com/sapegin/mrm/blob/master/packages/mrm-core/src/npm.js#L36

If you feel it, you can try to debug it and see where it crashes. 

For us I think it's almost impossible to debug without being able to get a hand on your environment and thus be able to reproduce the error

**Comment by RicardoAALL** [comment] 2023-05-09 00:25
Thank you!

I tried to do some debugging by cloning the create-japa repository and running through the installer, but it executed without a hitch. 

`npm init japa@latest` executes as expected on my Mac and Linux machines as well.

Strangely enough, I was able to successfully run the installer on Windows Server 2019 on an existing project. It still fails under an NX monorepo, however. No success on Windows 11 on my end either.

Seems the issue is solely with my Windows environments. Since it runs as exected through the cloned repo I haven't been able to debug it. I have tried searching but I haven't been able to find a way to debug an `npm init` command. I'm not sure what steps I should take to continue debugging on my end. Do you have any suggestions on how to proceed? 

Thanks again for the assistance.

**Comment by thetutlage** [comment] 2023-06-23 03:45
Closing, since not actionable

**Closed** 2023-06-23 03:46 UTC
